#整体基础配置TOML文件

switchMysql = true   #是否需要连接Mysql
switchRedis = false  #是否需要连接Redis
switchMongo = false  #是否需要连接Mongo

#Mysql相关配置
[mysql]
    address     =   "127.0.0.1"
    port        =   3306
    user        =   "root"
    password    =   "luoqiang3565893"
    db          =   "test"
    maxOpen     =   10          #最大连接数
    maxIdle     =   10          #最大空闲数
    charset     =   "utf8mb4"   #字符集

#Redis相关配置
[redis]

#Mongo相关配置
[mongo]